version: '3.8'

services:

  # See https://hub.docker.com/_/mongo/ for documentation about
  # MongoDB Docker images.
  mongodb-service:
    image: mongo:3.7
    environment:
<<<<<<< HEAD
      # MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: sdx
      MONGO_INITDB_ROOT_PASSWORD: passw
=======
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
>>>>>>> main
      MONGODB_DATA_DIR: /data/db
    volumes:
      # See https://docs.docker.com/storage/volumes/
      #
      # The 'Z' option tells Docker to label the content with a
      # private unshared label. Private volumes can only be used by
      # the current container.  See
      # https://docs.docker.com/engine/reference/commandline/run/
      - type: volume
        source: mongodb
        target: /data/db:Z

  sdx-controller-service:
    image: sdx-controller
    depends_on:
      - mongodb-service
    tty: true
    build: ./
    ports:
      - 8081:8080
    environment:
<<<<<<< HEAD
      # Use sdx-controller-mongodb service specified above.
      - MONGODB_CONNSTRING=mongodb://sdx:passw@sdx-controller-mongodb:27017/
      - SDX_HOST=aw-sdx-controller.renci.org
      - SDX_PORT=8081
      - SDX_VERSION=1.0.0
      - PUB_TOPIC=connection
      - SUB_QUEUE=sdx_q1
      - SUB_TOPIC=topo
      - SUB_QUEUE=topo
      - SUB_TOPIC=sdx_q1
      - MQ_HOST=aw-sdx-monitor.renci.org
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=sdx-config-test-1
=======
      # Use mongodb-service specified above.  Note that we do not use
      # the same MONGODB_CONNSTRING variable from .env here, because
      # that is helpful for running unit/integration tests.
      - MONGODB_CONNSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb-service:27017/
      - SDX_HOST=${SDX_HOST}
      - SDX_PORT=${SDX_PORT}
      - SDX_VERSION=${SDX_VERSION}
      - MQ_HOST=${MQ_HOST}
      - SUB_QUEUE=${SUB_QUEUE}
      - DB_NAME=${DB_NAME}
      - DB_CONFIG_TABLE_NAME=${DB_CONFIG_TABLE_NAME}
>>>>>>> main

  bapm-server-service:
    image: bapm-server
    tty: true
    build: ./bapm_server
    environment:
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - BAPM_MQ_HOST=${BAPM_MQ_HOST}
      - BAPM_EXCHANGE=${BAPM_EXCHANGE}
      - BAPM_QUEUE=${BAPM_QUEUE}
      - BAPM_ROUTING_KEY=${BAPM_ROUTING_KEY}

volumes:
  mongodb:
